[package]
name = "beamer-note-ify"
version = "0.1.0"
authors = ["Adrian Dawid <adriandwd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
strum = "0.19"
strum_macros = "0.19"
